version: '3.1'

services:

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: mnemotest
    ports:
      - 127.0.0.1:5432:5432
    # consider adding a mount for data if necessary      
