version: 2
jobs:
  build-and-test:
    docker:
    - image: cimg/elixir:1.14.0-browsers
      environment:
        DATABASE_URL: postgres://postgres:postgres@localhost/mnemo
    - image: cimg/postgres:14.5
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mnemo
    steps:
    - checkout
    - run:
        name: Install hex
        command: mix local.hex --force
    - run:
        name: Install rebar
        command: mix local.rebar --force
    - run:
        name: Install mix deps
        command: |
          cd src/mnemo;
          mix deps.get;
    - run:
        name: Install npm deps
        command: |
          cd src/mnemo;
          npm install --prefix=./assets;
    - run:
        name: Check eilixir formatting
        command: |
          cd src/mnemo;
          mix format --check-formatted --dry-run;
    - run:
        name: Run mix tests
        command: |
          cd src/mnemo;
          MIX_ENV=test mix test;
workflows:
  main:
    jobs:
    - build-and-test
  version: 2

# Original config.yml file:
# version: 2.1
# 
# description: Build and test Mnemo
# 
# jobs:
#   build-and-test:
#     docker:
#       - image: cimg/elixir:1.14.0-browsers
#         environment:
#           DATABASE_URL: postgres://postgres:postgres@localhost/mnemo
#       - image: cimg/postgres:14.5
#         environment:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: mnemo
#     steps:
#       - checkout
#       - run: 
#           name: \"Install hex\"
#           command: mix local.hex --force
#       - run:
#           name: \"Install rebar\"
#           command: mix local.rebar --force
#       - run:
#           name: \"Install mix deps\"
#           command: |
#             cd src/mnemo;
#             mix deps.get;
#       - run:
#           name: \"Install npm deps\"
#           command: |
#             cd src/mnemo;
#             npm install --prefix=./assets;
#       - run:
#           name: \"Check eilixir formatting\"
#           command: |
#             cd src/mnemo;
#             mix format --check-formatted --dry-run;
#       - run:
#           name: \"Run mix tests\"
#           command: |
#             cd src/mnemo;
#             MIX_ENV=test mix test;
# 
# workflows:
#   main:
#     jobs:
#       - build-and-test