version: 2.1

jobs: 
  build_and_test:
    docker:
      - image: elixir:1.14.0
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost/mnemo
            #     - image: cimg/postgres:14.5
            #       environment: 
            #         PGHOST: localhost
            #         PGUSER: postgres
            #         POSTGRES_USER: postgres
            #         POSTGRES_PASSWORD: postgres
            #         POSTGRES_DB: mnemo
    steps:
      - checkout
        #     - run:
        #         name: Wait for DB
        #         command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Build project
          command: |
            ls -al

workflows:
  main:
     jobs:
       - build_and_test
