version: 2.1

description: Build and test Mnemo

jobs:
  build-and-test:
    docker:
      - image: cimg/elixir:1.14.0-browsers
      - image: cimg/postgres:14.5
    steps:
      - checkout
      - run: 
          name: "Install hex"
          command: mix local.hex --force
      - run:
          name: "Install rebar"
          command: mix local.rebar --force
      - run:
          name: "Install mix deps"
          command: mix deps.get
      - run:
          name: "Install npm deps"
          command: npm install --prefix=./assets
      - run:
          name: "Check eilixir formatting"
          command: mix format --check-formatted --dry-run
      - run:
          name: "Run mix tests"
          command: MIX_ENV=test mix test

workflows:
  main:
    jobs:
      - build-and-test
