version: 2.1

jobs: 
  build_and_test:
    docker:
      - image: nikokozak/mnemo:2.0
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost/mnemo
            #     - image: cimg/postgres:14.5
            #       environment: 
            #         PGHOST: localhost
            #         PGUSER: postgres
            #         POSTGRES_USER: postgres
            #         POSTGRES_PASSWORD: postgres
            #         POSTGRES_DB: mnemo
    steps:
      - checkout
        #     - run:
        #         name: Wait for DB
        #         command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Preserve Logs
          command: exec 3>&1 1>>build_logs 2>&1
      - run:
          name: Migrate DB
          command: /app/bin/migrate 
      - store_artifacts:
          path: build_logs
          destination: build_logs
      

workflows:
  main:
     jobs:
       - build_and_test
